"use strict";
const { model } = require("../utils");

module.exports = (sequelize, DataTypes ) => {
    const Announcements = model(
        sequelize,
        "Announcements",
        {
            id: {
                field: "id",
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true,
                _autoGenerated: true,
            },
            userId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            regionId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            cityId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            categoryId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            price: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            currency: {
                type: DataTypes.ENUM('amd', 'usd', 'rub'),
                allowNull: true,
            },
            description: {
                type: DataTypes.TEXT,
                allowNull: false,
            }
        }, 
    );

    return Announcements;
};
