"use strict";
const { model } = require("../utils");

module.exports = (sequelize, DataTypes) => {
    const AssoUsersImages = model(
        sequelize,
        "AssoUsersImages",
        {
            id: {
                field: "id",
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true,
                _autoGenerated: true,
            },
            userId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            imageId: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
        },
    );

    return AssoUsersImages;
};
