"use strict";
const { model } = require("../utils");

module.exports = (sequelize, DataTypes ) => {
    const Locations = model(
        sequelize,
        "Locations",
        {
            id: {
                field: "id",
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true,
                _autoGenerated: true,
            },
            parentId: {
                type: DataTypes.INTEGER,
                allowNull: true,
            },
            name: {
                type: DataTypes.STRING,
                allowNull: false,
            },
            // region, city, province, etc...
            type: {
                type: DataTypes.STRING,
                allowNull: false,
            }
        },
        {
            timestamps: false,
            paranoid: false
        }
    );

    Locations.associate = function (models) {
        Locations.belongsTo(models["Locations"], {
            foreignKey: "parentId",
            as: "parent",
            onDelete: "CASCADE",
            onUpdate: "CASCADE",
        });
    };

    return Locations;
};
