"use strict";
const { model } = require("../utils");
const { numericHash } = require("../../utils");

module.exports = (sequelize, DataTypes) => {
    const Tags = model(
        sequelize,
        "Tags",
        {
            id: {
                field: "id",
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true,
                _autoGenerated: true,
                set() {
                    let value = this.getDataValue('id')
                    this.setDataValue('id', value);
                },
            },
            // This field important hash of tag's name. 
            // It will be used in time searching
            name: {
                type: DataTypes.STRING,
                allowNull: false,
            },
            // Partially hashed name ( only first and last chars )
            phName: {
                type: DataTypes.INTEGER.UNSIGNED,
                allowNull: false,
            },
            // Hashed name ( not partially )
            hName: {
                type: DataTypes.INTEGER.UNSIGNED,
                allowNull: false,
            },
            // Hached only first char
            hfChar: {
                type: DataTypes.INTEGER,
                allowNull: false,
            }
        }, 
        {
            indexes: [
                {
                    unique: true,
                    fields: ['hfChar', 'phName', 'hname']
                },
            ],
            timestamps: false,
        }
    );

    Tags.beforeCreate(async (tag) => {
        if(!tag.hName || !tag.phName || !tag.hfChar) {
            const { complete, partial, first } = numericHash.combined(tag.name);
            tag.hName = complete;
            tag.phName = partial;
            tag.hfChar = first;
        }
    });

    Tags.beforeUpdate(async (tag) => {
        const { complete, partial, first } = numericHash.combined(tag.name);
        tag.hName = complete;
        tag.phName = partial;
        tag.hfChar = first;
    });

    return Tags;
};
